// Exploring Logical operator to check multiple conditions

// Note => output generated by logical operator is always either true or false

// 1. Logical && (and) operator => It will only applicable or only gives true when all the operations or conditions are true

console.log(12 >= 12 && 12==12);


// 2. Logical || (or) operator => it gives output as true when at least one condition must be true

console.log(12<12 || 12==12);


// 3. Logical ! (not) operator => it gives output as if the given value is false but if given value is true output will be false

console.log(!(true))
